name: 🐛 Bug report
description: Report a bug to help us improve ASF-ui
labels: ["🐛 Bug", "🧐 Evaluation"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our bug report form is appropriate for you.
      options:
        - label: I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
          required: true
        - label: I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
          required: true
        - label: This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
          required: true
        - label: This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
          required: true
        - label: I cleared my cache and localStorage
          required: true
  - type: dropdown
    id: asf-version
    attributes:
      label: ASF version
      description: If you're using a different version than the current **[stable](https://github.com/JustArchiNET/ArchiSteamFarm/releases/latest)** or **[pre-release](https://github.com/JustArchiNET/ArchiSteamFarm/releases)**, ensure that your bug report is reproducible on one of the below.
      options:
        - Latest stable release
        - Latest pre-release
    validations:
      required: true
  - type: textarea
    id: asf-ui-version
    attributes:
      label: ASF-ui version
      description: Provide 7 character long hash in bottom right cornor of ASF-ui.
      placeholder: |
        c457dc3
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Short explanation of what you were going to do, what did you want to accomplish?
      placeholder: |
        I tried to create a new bot but got an error.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: |
        I expected that a new bot is added to ASF.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happened instead?
      placeholder: |
        My browsers console displays an exception.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Every command or action that happened after launching ASF, which leads to the bug.
      placeholder: |
        If launching ASF with provided configs (below) is everything that is needed, then this section is not mandatory.
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible reason/solution
      description: Not mandatory, but you can suggest a fix/reason for the bug, if known to you.
      placeholder: If you observed something peculiar about your issue that could help us locate and fix the culprit, this is the right place.
  - type: dropdown
    id: help
    attributes:
      label: Can you help us with this bug report?
      description: ASF-ui is offered for free and our resources are limited. Helping us increases the chance of fixing the problem.
      options:
        - Yes, I can code the solution myself and send a pull request
        - Somehow, I can test and offer feedback, but can't code
        - No, I don't have time, skills or willings for any of that
    validations:
      required: true
  - type: textarea
    id: global-config
    attributes:
      label: Global ASF.json config file
      description: The config can be found in `config` directory under `ASF.json` name. You can leave this field empty if not using one.
      placeholder: |
        Paste the file content here, no need for triple backtick tags

        Ensure that your config has redacted (but NOT removed) potentially-sensitive properties, such as:
        - IPCPassword (recommended)
        - SteamOwnerID (optionally)
        - WebProxy (optionally, if exposing private details)
        - WebProxyPassword (optionally, if exposing private details)
        - WebProxyUsername (optionally, if exposing private details)

        Redacting involves replacing sensitive details, for example with stars (***). You should refrain from removing config lines entirely, as their pure existence may be relevant and should be preserved.
      render: json
  - type: textarea
    id: bot-config
    attributes:
      label: BotName.json config of all affected bot instances
      description: Bot config files can be found in `config` directory, ending with `json` extension. You can leave this field empty if you don't have any defined.
      placeholder: |
        Paste the file content here, no need for triple backtick tags

        Ensure that your config has redacted (but NOT removed) potentially-sensitive properties, such as:
        - SteamLogin (mandatory)
        - SteamPassword (mandatory)
        - SteamMasterClanID (optionally)
        - SteamParentalCode (optionally)
        - SteamTradeToken (optionally)
        - SteamUserPermissions (optionally, only SteamIDs)

        Redacting involves replacing sensitive details, for example with stars (***). You should refrain from removing config lines entirely, as their pure existence may be relevant and should be preserved.
      render: json
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Everything else you consider worthy that we didn't ask for.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this bug report.